### ISSUE TITLE
Duration picker support

### ISSUE THREAD

**Issue by msankar1991** [kartik-v/yii2-widget-timepicker#11]
Awesome work to using this plugin with yii framework.

May I know is there any possibilities to implement the duration picker with current widget. I have found duration picker in bootstrap [https://github.com/koss-lebedev/bootstrap-duration-picker](https://github.com/koss-lebedev/bootstrap-duration-picker) and jquery also [http://www.jqueryscript.net/time-clock/Minimal-Duration-Picker-Plugin-For-jQuery-Bootstrap.html](http://www.jqueryscript.net/time-clock/Minimal-Duration-Picker-Plugin-For-jQuery-Bootstrap.html)

Is there any simple steps to implement duration picker with this widget based on above examples.

**Comment by kmindi** [comment]
Duration picking would be useful for me too.
