### ISSUE TITLE
TimePicker: focus on tab should go to hours not to last elements

### ISSUE THREAD

**Issue by tsdogs** [kartik-v/yii2-widget-timepicker#14]
When a user uses the keyboard tab to switch between inputs (or simply the input gets the focus), when there's a value in the TimePicker, the selection is on last element (AM, seconds or whatever is configured).

If I tab (and focus the input), the selected element should be the first one or at least the whole value.
As I can see this is an issue of the javascript part, though the original author hasn't fixed an issue since a long time.
I might try to fix this but first would like to know if it's a legitimate behaviour.

**Comment by tsdogs** [comment]
changing 
```javascript
'focus.timepicker': $.proxy(this.highlightUnit, this),
```
to
```javascript
'focus.timepicker': $.proxy(this.highlightHour, this),
```
should fix the problem. Though a click would first highlight the hour and then next click highlight the clicked element.

You think an option to enable this behaviour should be added?

**Comment by kartik-v** [comment]
This seems more related to the third party TimePicker plugin - but you can submit a PR to enhance this.

**Comment by tsdogs** [comment]
Yes, but you enhanced the code, fixed some bugs since the mainstream plug-in seems to be "stalled".
I might provide a PR but would you accept the change as reported above? Or do you require me to add an option to enable this behaviour?

[OT] BTW: how do you generate the minified version of the js? [/OT]

**Comment by kartik-v** [comment]
You can submit an enhancement by providing a configuration option to control the above.

You can generate a [minified version of the JS from here](http://refresh-sf.com)
