### ISSUE TITLE
Inline TimePicker Widget

### ISSUE THREAD

**Issue by Scentyoo** [kartik-v/yii2-widget-timepicker#2]
Is it possible to display the TimePicker-Widget inline? Especially for mobile applications/webpages it would be very nice if I don't have to press the time-button for the widget to appear.

![timepicker](https://cloud.githubusercontent.com/assets/3822672/7747973/75ee6c88-ffc0-11e4-9913-62f223ae5e83.PNG)

**Comment by kartik-v** [comment]
The widget currently uses the bootstrap-timepicker plugin that does the rendering. This would need the plugin code to be changed - so its better if this could be raised with plugin author.

**Comment by Scentyoo** [comment]
Ok, I'll try. Thanks! Great work anyway ;-)
