### ISSUE TITLE
Visualization problme when  used in TabularForm

### ISSUE THREAD

**Issue by bobonov** [kartik-v/yii2-widget-timepicker#4]
When used in tabular form it render behind the footer of the grid.
The div that contain the rows show scrollbars and the only way to visualize the widget is to scroll with the mouse wheel.
![schermata1](https://cloud.githubusercontent.com/assets/1412083/9874836/d719c012-5ba9-11e5-8260-6c80446c7dd7.png)
I think is a problem with this widget since the datetimepicker do not have this issue as it render above the footer, outside rows container.

**Comment by kartik-v** [comment]
This needs to be reported to the [plugin author](https://github.com/rendom/bootstrap-3-timepicker) for fix.

**Comment by bobonov** [comment]
I opened an issue
https://github.com/rendom/bootstrap-3-timepicker/issues/14
but the widget does not seem to be maintained anymore. There are issue and pull request without an answer since 1 year, last commit was 1 year ago as well.

But I see that the project from which was forked is alive again.
https://github.com/jdewit/bootstrap-timepicker
but it seem under heavy implementation (many bugs and pull request still on) therefore is not production ready.

**Comment by kartik-v** [comment]
@bobonov that's correct... will wait for a stable release of the best plugin and take it from there
