### ISSUE TITLE
bootstrap timepicker js is not found

### ISSUE THREAD

**Issue by ajkosh** [kartik-v/yii2-widget-timepicker#6]
after install yii2 widget ,when i m using timepicker ,it is giving me error in firbug 
bootstrap timepicker js not found

**Comment by harshitchaudhary** [comment]
I have encountered with the similar issue. timepicker not found. Here is the screenshot of the bug. 
![screenshot_2017-08-20_21-18-44](https://user-images.githubusercontent.com/4983996/29496298-3a391d4a-85ed-11e7-8884-f873275296eb.png)
